app = "jat-backend"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[env]
  FLASK_APP = "wsgi"
  FLASK_ENV = "production"
  SECRET_KEY = "albatros"
  DATABASE_URL="postgresql://postgres:2k5KgNpsX2McUor@jat-db.flycast:5432/postgres"
