app = "jat-backend"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-2x"
  memory = "1024mb"

[env]
  FLASK_APP = "wsgi"
  FLASK_ENV = "production"
  SECRET_KEY = "albatros"
  DATABASE_URL="postgresql://postgres:2k5KgNpsX2McUor@jat-db.flycast:5432/postgres"
  PYTHONPATH = "/app"
  REDIS_URL = "redis://default:b7574f6dc4084a11a41c26138aa73093@fly-jat.upstash.io:6379"

[deploy]
release_command = "/opt/venv/bin/flask db upgrade"


